// src/sources.js
// All configured French news sources with their RSS feeds and bias metadata

const SOURCES = [
  // ── GAUCHE ──────────────────────────────────────────────────────────────────
  {
    id: "mediapart",
    name: "Médiapart",
    url: "https://www.mediapart.fr/articles/feed",
    orientation: "gauche",
    orientationScore: 0,
    factuality: "haute",
    owner: "Indépendant (société de lecteurs)",
    ownerType: "indépendant",
    logo: "MP",
    color: "#e74c3c",
    founded: 2008,
  },
  {
    id: "humanite",
    name: "L'Humanité",
    url: "https://www.humanite.fr/rss.xml",
    orientation: "gauche",
    orientationScore: 0,
    factuality: "moyenne",
    owner: "Société coopérative de presse",
    ownerType: "indépendant",
    logo: "HUM",
    color: "#c0392b",
    founded: 1904,
  },
  {
    id: "blast",
    name: "Blast",
    url: "https://www.blast-info.fr/feed.rss",
    orientation: "gauche",
    orientationScore: 0,
    factuality: "moyenne",
    owner: "Indépendant (financement participatif)",
    ownerType: "indépendant",
    logo: "BL",
    color: "#8e44ad",
    founded: 2021,
  },
  {
    id: "liberation",
    name: "Libération",
    url: "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml",
    orientation: "gauche",
    orientationScore: 1,
    factuality: "haute",
    owner: "Altice / Patrick Drahi",
    ownerType: "milliardaire télécom",
    logo: "LIB",
    color: "#c0392b",
    founded: 1973,
  },
  {
    id: "lobs",
    name: "L'Obs",
    url: "https://www.nouvelobs.com/rss.xml",
    orientation: "centre-gauche",
    orientationScore: 2,
    factuality: "haute",
    owner: "Groupe Le Monde (Niel/Pigasse)",
    ownerType: "milliardaires indépendants",
    logo: "OBS",
    color: "#d35400",
    founded: 1964,
  },

  // ── CENTRE-GAUCHE ────────────────────────────────────────────────────────────
  {
    id: "lemonde",
    name: "Le Monde",
    url: "https://www.lemonde.fr/rss/une.xml",
    orientation: "centre-gauche",
    orientationScore: 2,
    factuality: "haute",
    owner: "Xavier Niel / Matthieu Pigasse",
    ownerType: "milliardaires indépendants",
    logo: "LM",
    color: "#1a1a2e",
    founded: 1944,
  },
  {
    id: "marianne",
    name: "Marianne",
    url: "https://www.marianne.net/rss.xml",
    orientation: "centre",
    orientationScore: 3,
    factuality: "moyenne",
    owner: "Czech Media Invest (Daniel Kretinsky)",
    ownerType: "milliardaire étranger",
    logo: "MAR",
    color: "#2980b9",
    founded: 1997,
  },

  // ── CENTRE ──────────────────────────────────────────────────────────────────
  {
    id: "bfmtv",
    name: "BFMTV",
    url: "https://www.bfmtv.com/rss/news-24-7/",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "Altice / Patrick Drahi",
    ownerType: "milliardaire télécom",
    logo: "BFM",
    color: "#2980b9",
    founded: 2005,
  },
  {
    id: "franceinfo",
    name: "France Info",
    url: "https://www.francetvinfo.fr/titres.rss",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "France Télévisions (public)",
    ownerType: "service public",
    logo: "FI",
    color: "#e67e22",
    founded: 1987,
  },
  {
    id: "france24",
    name: "France 24",
    url: "https://www.france24.com/fr/rss",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "France Médias Monde (public)",
    ownerType: "service public",
    logo: "F24",
    color: "#16a085",
    founded: 2006,
  },
  {
    id: "leparisien",
    name: "Le Parisien",
    url: "https://feeds.leparisien.fr/leparisien/rss",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "Bernard Arnault (LVMH)",
    ownerType: "milliardaire luxe",
    logo: "LP",
    color: "#d35400",
    founded: 1944,
  },
  {
    id: "20minutes",
    name: "20 Minutes",
    url: "https://www.20minutes.fr/feeds/rss/news.xml",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "Rossel (Belgique)",
    ownerType: "groupe de presse",
    logo: "20M",
    color: "#27ae60",
    founded: 2002,
  },
  {
    id: "ouestfrance",
    name: "Ouest-France",
    url: "https://www.ouest-france.fr/rss-en-continu.xml",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "Association indépendante (SIPA)",
    ownerType: "indépendant",
    logo: "OF",
    color: "#2c3e50",
    founded: 1944,
  },
  {
    id: "rtl",
    name: "RTL",
    url: "https://www.rtl.fr/rss",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "M6 Group / RTL Group",
    ownerType: "groupe audiovisuel",
    logo: "RTL",
    color: "#e74c3c",
    founded: 1933,
  },
  {
    id: "lacroix",
    name: "La Croix",
    url: "https://www.la-croix.com/RSS/UNIVERS",
    orientation: "centre",
    orientationScore: 3,
    factuality: "haute",
    owner: "Groupe Bayard",
    ownerType: "groupe catholique",
    logo: "CRX",
    color: "#8e44ad",
    founded: 1883,
  },

  // ── CENTRE-DROITE ────────────────────────────────────────────────────────────
  {
    id: "lesechos",
    name: "Les Échos",
    url: "https://www.lesechos.fr/rss/rss_une.xml",
    orientation: "centre-droite",
    orientationScore: 4,
    factuality: "haute",
    owner: "Bernard Arnault (LVMH)",
    ownerType: "milliardaire luxe",
    logo: "LE",
    color: "#16a085",
    founded: 1908,
  },
  {
    id: "lexpress",
    name: "L'Express",
    url: "https://www.lexpress.fr/rss/alaune.xml",
    orientation: "centre-droite",
    orientationScore: 4,
    factuality: "haute",
    owner: "Alain Weill / Altice",
    ownerType: "milliardaire télécom",
    logo: "EXP",
    color: "#c0392b",
    founded: 1953,
  },

  // ── DROITE ──────────────────────────────────────────────────────────────────
  {
    id: "lefigaro",
    name: "Le Figaro",
    url: "https://www.lefigaro.fr/rss/figaro_actualites.xml",
    orientation: "droite",
    orientationScore: 5,
    factuality: "haute",
    owner: "Famille Dassault (SOCPRESSE)",
    ownerType: "groupe industriel",
    logo: "LF",
    color: "#8b1a1a",
    founded: 1826,
  },
  {
    id: "lepoint",
    name: "Le Point",
    url: "https://www.lepoint.fr/rss.xml",
    orientation: "droite",
    orientationScore: 5,
    factuality: "haute",
    owner: "François Pinault",
    ownerType: "milliardaire luxe",
    logo: "PT",
    color: "#2c3e50",
    founded: 1972,
  },
  {
    id: "contrepoints",
    name: "Contrepoints",
    url: "https://www.contrepoints.org/feed",
    orientation: "droite",
    orientationScore: 5,
    factuality: "moyenne",
    owner: "Association libérale indépendante",
    ownerType: "indépendant",
    logo: "CP",
    color: "#7f8c8d",
    founded: 2009,
  },

  // ── DROITE EXTRÊME ───────────────────────────────────────────────────────────
  {
    id: "cnews",
    name: "CNews",
    url: "https://www.cnews.fr/rss.xml",
    orientation: "droite extrême",
    orientationScore: 6,
    factuality: "mixte",
    owner: "Vincent Bolloré (Vivendi)",
    ownerType: "milliardaire conservateur",
    logo: "CN",
    color: "#2c3e50",
    founded: 1999,
  },
  {
    id: "valeursactuelles",
    name: "Valeurs Actuelles",
    url: "https://www.valeursactuelles.com/feed",
    orientation: "droite extrême",
    orientationScore: 6,
    factuality: "faible",
    owner: "Groupe Valmonde",
    ownerType: "groupe conservateur",
    logo: "VA",
    color: "#7f8c8d",
    founded: 1966,
  },
];

const getSource = (id) => SOURCES.find((s) => s.id === id) || null;

const getOrientationBucket = (score) => {
  if (score <= 1) return "gauche";
  if (score <= 3) return "centre";
  return "droite";
};

module.exports = { SOURCES, getSource, getOrientationBucket };
